services:
  stats-server:
    build: ./statsService/server
    image: explore-with-me-server
    container_name: explore-with-me-server
    ports:
      - "9090:8080"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-stats
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=explore
      - POSTGRES_USER=explore
      - POSTGRES_DB=explore-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10